package videomovies.Model;

/**
 * Created by DAM on 4/5/15.
 */
public enum Genre {
    ACTION, ADVENTURE, ANIMATION, COMEDY, CRIME, DOCUMENTARY, DRAMA, FANTASY, HISTORY, HORROR, MUSIC, ROMANCE, SCIFI, SPORT, THRILLER, WAR, WESTREN
}
